PARAENGINE_NGISIHZIXIL_VER0001
======================
Do NOT edit this file
======================

This file is the signature file for ParaEngine. It is used for locating the root of ParaEngine executable.
Currently it is only used for ParaX model exporter. Please only put this file to the root directory. 